spring:
  config:
    import: env.properties
  profiles:
    active: ${ACTIVE}

api:
  version: /api/v1

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: ${LOCAL_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: ${LOCAL_JPA_DIALECT}

server:
  port: ${LOCAL_PORT}

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASSWORD}

server:
  port: ${DEV_PORT}

#spring:
#  profiles:
#    active: @spring.profiles.active@
#  datasource:
#    url: jdbc:postgresql://localhost:5432/finance_records
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#server:
#  port: 9000
#
#api:
#  version: /api/v1